### ISSUE TITLE
[BACKEND] Implement passage api

### ISSUE THREAD

**Issue by giannispan** [cvcio/mediawatch#17]
New Proto:  

Add new field language in passage model : mediawatch ->models passage model.go, language string (feed language)
Text field: string type, Type fileds : enamuration TRIM_LEFT, TRIM_RIGHT, SPLIT

mediawatch -> proto (v2).

Service:

1) Create passage 
2) List passages (with language filter)

**Comment by andefined** [comment]
merged #18
